device: cpu       # 或者 cuda/mps
weights:
  doclayout_yolo: Structure/doclayout_yolo_docstructbench_imgsz1280_2501.pt
  layoutreader: Relation
models_dir: model_weight
layout_config:
  model: doclayout_yolo
  reader:
    name: layoutreader
chat_config:
  backend: api
api_config:
  url: https://api.deepseek.com/v1
  model_name: deepseek-reasoner
  api_key: sk-816d9a802e5f4c8ab73459a40791d7db
